Update bulkuser
added more password options

diff --git a/Modulos/bulkuser b/Modulos/bulkuser
--- a/Modulos/bulkuser
+++ b/Modulos/bulkuser
@@ -1,8 +1,18 @@
 #!/bin/bash
 IP=$(cat /etc/IP)
 generate_random_pass() {
-    local length=$1
+    local type=$1
+    local length=$2
+    if [[ $type -eq 1 ]]
+    then
+    local chars=( {0..9} )
+    elif [[ $type -eq 2 ]]
+    then
+    local chars=({a..z} {0..9} )
+    elif [[ $type -eq 3 ]]
+    then
     local chars=({a..z} {A..Z} {0..9} )
+    fi
     local str=""
 
     for (( i=0; i<$length; i++)); do
@@ -14,11 +24,12 @@ generate_random_pass() {
 }
 check_username() {
     awk -F : ' { print $1 }' /etc/passwd > /tmp/users
+    local rep=0
     if grep -Fxq "$1" /tmp/users
     then
-        tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "User {$1} already exists." ; echo "" ; tput sgr0
-        exit 1
+        local rep=1
     fi
+    echo "$rep"
 }
 
 
@@ -43,6 +54,17 @@ if [[ -z $startnum ]] || [[ ${startnum} != ?(+|-)+([0-9]) ]]
 then
 echo ""
 tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Invalid starting number." ; echo "" ; tput sgr0
+	exit 1
+fi
+echo -e "\033[1;32mPassword types\033[1;37m: "
+echo -e "\033[1;31m        [\033[1;36m1\033[1;31m]\033[1;33m Numeric"
+echo -e "\033[1;31m        [\033[1;36m2\033[1;31m]\033[1;33m Alphanumeric lower case"
+echo -e "\033[1;31m        [\033[1;36m3\033[1;31m]\033[1;33m Alphanumeric mixed case"
+echo -ne "\033[1;32m◇ Choose\033[1;37m: "; read passtype
+if [[ -z $passtype ]] || [[ ${passtype} != ?(+|-)+([0-9]) ]]
+then
+echo ""
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Empty or invalid type." ; echo "" ; tput sgr0
 	exit 1
 fi
 echo -ne "\033[1;32mPassword length\033[1;37m: "; read passlength
@@ -70,8 +92,16 @@ fi
 echo "Host,Username,Password,Limit,Exp">/tmp/bulkusers
 for (( i=$startnum; i<=($startnum+$num); i++ )); do
     username=$name$i
-    check_username $username
-    password=$(generate_random_pass $passlength)
+    check=$(check_username $username)
+    if [[ check -eq 1 ]]
+    then
+    tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "$username already exists." ; echo "" ; tput sgr0
+    exit 1
+    fi
+done
+for (( i=$startnum; i<=($startnum+$num); i++ )); do
+    username=$name$i
+    password=$(generate_random_pass $passtype $passlength)
     pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
     useradd -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
     echo "$password" >/etc/VPSManager/senha/$username
